### ISSUE TITLE
Need Help with config

### ISSUE THREAD

**Issue by ketgg** [elythh/flake#1]
Hey, I was trying to install your config on Nixos, the `nixos-install` step went fine, after rebooting I did `home-manager` step (Had to remove elythh/private repo from home/gwen/home.nix otherwise it was asking for username, password) and everything went fine.
Later I put `exec awesome` in .`xinitrc` and use `startx` to start awesome, I get following screen

![IMG20230927064318.jpg](https://github.com/elythh/dotfiles/assets/105774228/7a8159a8-48b8-47cd-9780-75be71729cf0)

Am I missing some step or is there something wrong with awesome config?
 
Can you help me with this please, Thanks!

**Comment by elythh** [comment]
Hey ! Do you see any error logs on startup ? The issue might be related to that https://github.com/chadcat7/crystal/issues/13#issuecomment-1658047867
Try it and keep me informed 😄

**Comment by ketgg** [comment]
Hey thankyou for the reply, I have built the file `liblua_pam.so`, can you tell me where to replace it? (sorry I am new to Nixos) 

Edit: Ok I found it nvm (sorry for noob questions lol),

but still I dont see any changes its the same, there are two Awesome windows in top bar, also when I right click I see two menus  one is the customized one and other is default one

![Capture](https://github.com/elythh/dotfiles/assets/105774228/e1c78e38-b65a-47ac-958a-b10e6d108cbf)

![Capture0](https://github.com/elythh/dotfiles/assets/105774228/fac5a754-2d58-46df-be26-206cac165c2d)

**Comment by elythh** [comment]
Can you try to use https://github.com/gmdfalk/awmtt to see the logs in your terminal ?

**Comment by elythh** [comment]
Is the config/keys.lua file created ?

**Comment by ketgg** [comment]
> Is the config/keys.lua file created ?

nope there is no keys.lua file in `~/.config/awesome/config`

**Comment by elythh** [comment]
oh I have an idea then 😄 
You need to create a file at `~/.config/awesome/config/keys.lua` with the following : 
```
local M = {
 openweatherapi = "your_openweather_api_key",
 password = "i forgot whats it's for tbh",
 coordinates = { "X", "Y" },
}
```

Those are for the weather widget. If you put random value it's ok for now

**Comment by ketgg** [comment]
> oh I have an idea then 😄 You need to create a file at `~/.config/awesome/config/keys.lua` with the following :
> 
> ```
> local M = {
>  openweatherapi = "your_openweather_api_key",
>  password = "i forgot whats it's for tbh",
>  coordinates = { "X", "Y" },
> }
> ```
> 
> Those are for the weather widget. If you put random value it's ok for now

I think it worked but I am getting this error as well
![Capture1](https://github.com/elythh/dotfiles/assets/105774228/847b3f03-8fe8-4904-943f-f27e5e407dff)

**Comment by elythh** [comment]
Oh yeah sorry. This one is due to the `autostart.lua` file. You need to delete the line about `aw-qt`. And any other else you might not find useful for you

**Comment by ketgg** [comment]
My wallpapaer doesnot get set, I get black wallpaper
Also how can I switch to hyprland

**Comment by elythh** [comment]
To switch to Hyprland you need to launch it using `Hyprland` after login in with tty

**Comment by elythh** [comment]
For the wallpaper. Try the shortcut in the awesome keybind config to select it by yourself

**Comment by elythh** [comment]
Also i'm sorry i'm currently working on the hyprland config so it might not work right now

**Comment by ketgg** [comment]
Okay thankyou for your response and help 😊
