### ISSUE TITLE
Need help with Nix config

### ISSUE THREAD

**Issue by ketgg** [elythh/flake#7]
Hello, how can I use your hyprland config? Does it install automatically after home-manager switch or do I have to make some changes in config?

**Comment by elythh** [comment]
Hey ! I am no longer using hyprland, I switched back to awesomewm. I am using [chadchat's](https://github.com/chadcat7/crystal/tree/aura) config.

You should be able to use it after doing the home-manager switch yes

**Comment by elythh** [comment]
also, if you encounter any issue with awesome, try following these steps https://github.com/chadcat7/crystal/issues/13#issuecomment-1658047867

**Comment by ketgg** [comment]
Hey, I am trying to setup his awesome config on nix as well, can you please list the steps in brief you did to make it work.

**Comment by elythh** [comment]
1. Install NixOS
2. Use home-manager to install awesomewm
3. Forked his config to my own repo (https://github.com/elythh/nixdots/tree/awesome-v2) 
4. Changed `home.nix` to clone the config under `~/.config/awesome` https://github.com/elythh/nixdots/blob/main/home/gwen/home.nix#L79
5. Built liblua_pam using the linked guide above
6. Created the directories `~/.cache/awesome` and `~/.cache/awesome/json`
7. Restart

I will update the README with the detailed steps but I can't remember exactly, so if you encounter any issue let me know and I'll try to help you

**Comment by ketgg** [comment]
Thanks a lot, I will try again from step 1

**Comment by elythh** [comment]
For the first 2 steps i think you can find the commands here. Using my dotfile the default machine is `thinkpad` and the default user is `gwen`
https://github.com/chadcat7/crystal#installation

**Comment by ketgg** [comment]
Aight thanks

**Comment by elythh** [comment]
Also you won't *only* need awesome, chadcat listed every required packages 
`awesome-git zsh pamixer imagemagick ncmpcpp mpd mpDris2 neofetch brightnessctl inotifywait uptime brillo networkmanager bluetoothctl picom redshift wezterm` 
So make sure to install these too using home-manager/nix

**Comment by ketgg** [comment]
Hey I did all the steps I can see the config now but I am getting some error here, also I am able to move the cursor but clicks are not working.
![IMG20231202222533.jpg](https://github.com/elythh/nixdots/assets/105774228/c679bf51-a3d8-4c30-b740-603320d48f6c)

![IMG20231202222554.jpg](https://github.com/elythh/nixdots/assets/105774228/fcc0ca3c-cddf-46b1-a803-e57abb8a5d98)

I am having a 2560x1600 display on my laptop

**Comment by elythh** [comment]
Try restarting awesome once by pressing mod + ctrl + r

**Comment by ketgg** [comment]
> Try restarting awesome once by pressing mod + ctrl + r

Nothing is happening

**Comment by elythh** [comment]
For the display size, you will have to modify the config. Basically replace every `1920` and `1080` by your resolution. For example for the bar it's at https://github.com/elythh/nixdots/blob/awesome-v2/ui/bar/init.lua#L23

**Comment by ketgg** [comment]
Aight

**Comment by elythh** [comment]
Basically I have the two exact same error as you when first starting awesome, I haven't been able to investigate yet but my workaround is to restart awesome using [that](https://github.com/elythh/nixdots/blob/awesome-v2/main/bindings/bindings.lua#L12) binding and after it works fine

**Comment by ketgg** [comment]
Ohh I see its like my screen is froze keys and mouse clicks are not working, I can only move mouse

**Comment by elythh** [comment]
Oh that's odd, I have not experienced that I think. You could try logging into tty (no graphical interface) and typing startx to see the output errors

**Comment by ketgg** [comment]
I tried with startx I am not getting any notifications about error but still could only move my mouse and only mod+shift+q is working to exit out of awesome

**Comment by ketgg** [comment]
> also, if you encounter any issue with awesome, try following these steps [chadcat7/crystal#13 (comment)](https://github.com/chadcat7/crystal/issues/13#issuecomment-1658047867)

Hey, where should I place the liblua_pam file 

I am getting this error when trying in VirtualBox
![image_2023-12-03_134729405](https://github.com/elythh/nixdots/assets/105774228/e46a8ac7-f195-461b-bb62-c7ad05215002)

**Comment by elythh** [comment]
Hey, right in the ~/.config/awesome folder

**Comment by ketgg** [comment]
> Hey, right in the ~/.config/awesome folder

I placed the file in the same folder but still I am getting the error

**Comment by elythh** [comment]
Did you build it in the VM ? You might not be able to re-use the one you built before

**Comment by ketgg** [comment]
Yes

> Did you build it in the VM ? You might not be able to re-use the one you built before

**Comment by ketgg** [comment]
Can you share the contents of desktop.json

**Comment by elythh** [comment]
Oh sorry I've been busy at work and forgot to answer.

```
[{"row":1,"col":1,"widget":{"exec":"nemo trash:/","icon":"/nix/store/3wpdmiaszdpga7sdax0xj37q7kjs6hqs-reversal/share/icons/reversal-dark/places/48/trash-empty.svg","label":"Trash"}}]
```
here you are, I basically only have a Trash icon

**Comment by ketgg** [comment]
Thanks, I got it working on Arch Linux!

**Comment by elythh** [comment]
awesome !
